### ISSUE TITLE
How to visualize

### ISSUE THREAD

**Issue by May525116** [lab-sun/PolarPoint-BEV#2]
Hello, I would like to ask, what method was used to create this kind of visual image in your paper? Matplotlib? TensorBoard? Or other codes and tools? Is there any visual content like this in your public code? Looking forward to your reply!
![可视化](https://github.com/lab-sun/PolarPoint-BEV/assets/114332399/60266fa9-13eb-4872-97d7-a1a11f9949d6)

**Comment by 1146065545** [comment]
如果您说的是图片中的小车，用的应该是carla，如果说的是图中的极点我还没有试，希望对您有帮助

**Comment by May525116** [comment]
我的意思是关于这些极点（三类点），如何生成到了polarpoint bev map中。

**Comment by May525116** [comment]
我好像明白了，应该是用Matplotlib的一些库，将张量转换成了图片，实现了可视化。目前我还在寻找这三类语义点的可视化方法，是否是在可视化的时候一起显示了出来，还是添加了一些其他的操作。

**Comment by fyctime052** [comment]
These examples are made by using the codes. The function of these codes are quite simple. Take the polar point BEV map with normal configuration (16x27) for example, the number of layer is 16 and number of subsections in each layer is 27. So, as long as you know the parameters of FOV, interval of different layer (given in paper) along with the radius of first layer (3.5 meters), you can draw the visualized results. Hope this answer address you question.

**Comment by May525116** [comment]
Thank you very much for your answer！！！

**Comment by 1146065545** [comment]
> Thank you very much for your answer！！！

请问您训练的效果怎么样呢，我这里得到的结果似乎不理想

**Comment by May525116** [comment]
> > Thank you very much for your answer！！！
> 
> 请问您训练的效果怎么样呢，我这里得到的结果似乎不理想

也不是很理想，不过我主要是参考作者的思路和一些模块的设计。

**Comment by 1146065545** [comment]
> > > Thank you very much for your answer！！！
> > 
> > 
> > 请问您训练的效果怎么样呢，我这里得到的结果似乎不理想
> 
> 也不是很理想，不过我主要是参考作者的思路和一些模块的设计。

抱歉我收回我的问题，我发现之所以不理想是因为我没有正确的加载模型，在修改之后，我可以得到几乎相同的结果了，但是我还是发现在训练过程中，val_loss会逐渐增大，请问您也有相同的问题吗？
